name: Publish Package to npmjs
on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
      
permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install
        working-directory: ${{ inputs.directory }}
      
      - name: Check linting
        run: npm run lint:ci
        working-directory: ${{ inputs.directory }}
      
      - name: Build
        run: npm run build
        working-directory: ${{ inputs.directory }}
        
      - name: Clean install a project
        run: npm ci
        working-directory: ${{ inputs.directory }}
      
      - name: Publish to npm
        run: npm publish --provenance --access public
        working-directory: ${{ inputs.directory }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}