name: Publish Generator to npmjs
on:
  push:
    branches:
      - main      
    paths:
      - 'packages/generator/**'
      - 'biome.json'
      - '.github/workflows/publish-generator.yml'
      - '.github/workflows/npm-publish-reusable.yml'
      
permissions:
  contents: read
  id-token: write

jobs:
  call-publishing-workflow:
    if: ${{ !contains(github.event.head_commit.message, 'no-publish') }}
    uses: ./.github/workflows/publish-reusable.yml
    secrets: inherit
    with:
      directory: ./packages/generator
